name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  DOTNET_SYSTEM_NET_HTTP_USESOCKETSHTTPHANDLER: 0

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
    - uses: browser-actions/setup-chrome@v1
    - name: Install development certificates
      run: dotnet dev-certs https --trust
    - name: Run unit tests
      run: dotnet test --filter 'FullyQualifiedName~.UnitTests'
    - name: Run integration tests
      run: dotnet test --filter 'FullyQualifiedName~.TestApps.IntegrationTests'