name: CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Warmup
      run: curl https://idsvrtst.azurewebsites.net/.well-known/openid-configuration
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - uses: browser-actions/setup-chrome@v1
    - name: Run tests
      run: dotnet test --filter 'FullyQualifiedName!~ShouldIntegrateWithAuth0'
      env: 
        OIDCPROXY__AUTH0__AUDIENCE: ${{ secrets.OIDCPROXY__AUTH0__AUDIENCE }}
        OIDCPROXY__AUTH0__CLIENTID: ${{ secrets.OIDCPROXY__AUTH0__CLIENTID }}
        OIDCPROXY__AUTH0__CLIENTSECRET: ${{ secrets.OIDCPROXY__AUTH0__CLIENTSECRET }}
        OIDCPROXY__AUTH0__DOMAIN: ${{ secrets.OIDCPROXY__AUTH0__DOMAIN }}
        AUTH0__PASSWORD: ${{ secrets.AUTH0__PASSWORD }}
        AUTH0__USERNAME: ${{ secrets.AUTH0__USERNAME }}