name: Automatic updates

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'debug'
        type: choice
        options:
        - info
        - warning
        - debug
        
  schedule:
    - cron:  '0 8 * * *'

jobs:
  update:
    runs-on: ubuntu-latest
    name: Update dependencies
    steps:
      - name: Nukeeper
        id: nukeeper
        uses: nukeeperdotnet/nukeeper-action@0.1