name: Automatic updates

on:
  schedule:
    - cron:  '0 8 * * *'

jobs:
  update:
    runs-on: ubuntu-latest
    name: Update dependencies
    steps:
      - name: Nukeeper
        id: nukeeper
        uses: nukeeperdotnet/nukeeper-action@0.1